### ISSUE TITLE
Inquiring about CAMELYON17

### ISSUE THREAD

**Issue by xuanxu92** [jcboyd/cdpath21-gan#2]
Hi, this is a great work for whole slide images. I see that in utils.py it mentions to use camelyonpatch_level_2_split_train_x.h5 for train. Is this file from PatchCamelyon? Because I check the PatchCamelyon github, they mentions that they use Camelyon16. Could you please tell me which Camelyon dataset you use? Thanks!

**Comment by jcboyd** [comment]
Hi, thanks for your interest!

The naming convention was chosen to be compatible with PCam, but the datasets are indeed customised from CAMELYON17 at full 40x.

I have added a data folder with some instructions for creating our dataset:

https://github.com/jcboyd/cdpath21-gan/blob/main/data/README.md
